### ISSUE TITLE
Bad indentation with php mixed with HTML

### ISSUE THREAD

**Issue by jepser** [phpfmt/sublime-phpfmt#224]
I have php mixed with HTML and it doesn't indent well and puts all php without indent
![image](https://cloud.githubusercontent.com/assets/175774/12028149/54346260-ad98-11e5-97ce-417be1cbb2e3.png)

Also on save file adds tabs to HTML indent:
![image](https://cloud.githubusercontent.com/assets/175774/12028155/7b30659e-ad98-11e5-83a1-d2b857108211.png)
And after a save:
![image](https://cloud.githubusercontent.com/assets/175774/12028162/890c7e96-ad98-11e5-8618-598340fc60e0.png)

**Comment by ccirello** [comment]
Have you tried using AlignPHPCode pass?

**Comment by jepser** [comment]
I tried with this configuration:
```{
	"indent_with_space": 4,
	"passes":
	[
		"AlignPHPCode"
	],
	"php_bin": "/Applications/MAMP/bin/php/php5.6.10/bin/php",
	"version": 4
}```

And this is the result:

![image](https://cloud.githubusercontent.com/assets/175774/12028220/7b96018c-ad99-11e5-80fe-1d6bf5e145c8.png)

**Comment by jepser** [comment]
Also the "on save" over indent:

![image](https://cloud.githubusercontent.com/assets/175774/12028234/be25dc66-ad99-11e5-987e-edc2127b03f1.png)

Save and:
![image](https://cloud.githubusercontent.com/assets/175774/12028245/d9fa0994-ad99-11e5-8f27-4477480d695e.png)

**Comment by ccirello** [comment]
I see. I am afraid there is not a fix for this issue. The whole problem is that phpfmt formats PHP code, and not HTML code. Also, we cannot assume that PHP will always be surrounded by HTML - it fits within any arbitrary format, such XML, HTML, binary, JSON etc. So fixing against HTML is not really possible because there is not sure way to tell apart these file formats. Perhaps in future, someone comes up with a HTMLfmt which will arrange for this cases. I am sorry. 

Perhaps, what you could disable `phpfmt: format on save` option and prevent such headache.
